name: Backend CI/CD Pipeline

on:
  push:
    branches: [ main, develop, master ]  # 원하는 브랜치 추가
  pull_request:
    branches: [ main, develop, master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Grant execute permission to gradlew
        run: chmod +x ./gradlew

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Maven/Gradle
        run: |
            ./gradlew build -x test

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build and push Docker image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        run: |
          docker build -t $ECR_REGISTRY/kgat-backend:${{ github.sha }} -t $ECR_REGISTRY/kgat-backend:latest .
          docker push $ECR_REGISTRY/kgat-backend:${{ github.sha }}
          docker push $ECR_REGISTRY/kgat-backend:latest

      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd ~/deployment
            AWS_ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
            sed -i "s|image: .*kgat-backend:.*|image: ${{ steps.login-ecr.outputs.registry }}/kgat-backend:${{ github.sha }}|" backend/kgat-backend.yaml
            kubectl apply -f backend-deployment.yaml
            kubectl rollout restart deployment/kgat-backend
